name: slotly
description: "A modern responsive Slotly booking & appointment application frontend."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0          
  flutter_riverpod: ^2.4.0 
  riverpod_annotation: ^2.3.0
  cupertino_icons: ^1.0.8
  url_strategy: ^0.3.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
